fix: changelog validation bugfix (#697)

diff --git a/.github/workflows/validate-changelog.yaml b/.github/workflows/validate-changelog.yaml
--- a/.github/workflows/validate-changelog.yaml
+++ b/.github/workflows/validate-changelog.yaml
@@ -16,16 +16,16 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-changelog') }}
     steps:
-      - uses: actions/checkout@v6
-      
-      - uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
-        id: changed-files
+      - uses: actions/checkout@v4
         with:
-          files: CHANGELOG.md
+          fetch-depth: 0
 
       - name: Check CHANGELOG.md updated
-        if: steps.changed-files.outputs.any_changed != 'true'
         run: |
-          echo "::error::CHANGELOG.md has not been updated. Please update the changelog or add the 'skip-changelog' label to opt out."
-          exit 1
+          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q '^CHANGELOG.md$'; then
+            echo "CHANGELOG.md has been updated."
+          else
+            echo "::error::CHANGELOG.md has not been updated. Please update the changelog or add the 'skip-changelog' label to opt out."
+            exit 1
+          fi
 
